spring:
  application:
    name: banking-service

  config:
    import: classpath:/info/info.yaml

  # H2 DB ??
  datasource:
    url: jdbc:mysql://localhost:3306/ourdeal?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: mysqluser
    password: rootpassword  # 기본적으로 비밀번호 없음

  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console  # 브라우저에서 접속할 콘솔 URL
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 프로젝트에 맞게 'create', 'validate' 등 변경 가능
    show-sql: true
    properties:
      hibernate:
        format_sql: true